### PR TITLE
java solution leetcode two_sum problem

### PR DESCRIPTION
**Pull request by robinsonvs**
- possible solution in Java
- I adjusted some folders to be able to separate the solutions by language types

### CODE REVIEW

**Review by arthur404dev — CHANGES_REQUESTED** [review]
The solution is pretty sweet, and we also have a test scenario in place.

And even though I like the folder structure I think we'll have too many nested folders as the project grows. The file extension should be enough for the separation between languages IMO.

Would you mind changing to that structure?

**Comment by robinsonvs** [comment]
I'm going to close this pr and open another one ok

**Comment by robinsonvs** [comment]
removed the folders as we talked

**Review by arthur404dev — APPROVED** [review]
Great solution (: thanks for refactoring to fit the rest of the project

**Pull request merged**
